### ISSUE TITLE
UI / UX comments

### ISSUE THREAD

**Issue by msachi** [facn5/Its-show-time#9]
Your app looks and feels great, well done!

Just a few minor comments on the user experience:
- It's not clear what the grey circular button does, you need to press it to find out
- Anything clickable should have a `cursor: pointer;` set on it
- I didn't initially understand the message 'Your deleted items can't be backed-up', you probably meant 'recovered' rather than 'backed up'. Consider rephrasing

**Comment by Bear-Coding** [comment]
Can you take a look on the current UI?  :children_crossing:
